name: artist_pro
description: "Modern app for musicians and bands to manage songs, shows and finances."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  table_calendar: ^3.0.9
  fl_chart: ^0.66.0
  reorderable_grid_view: ^2.2.7
  share_plus: ^7.2.1
  uuid: ^4.3.3
  markdown: ^7.2.1
  file_picker: ^6.1.1
  csv: ^6.0.0
  pdf: ^3.10.7
  printing: ^5.12.0
  url_launcher: ^6.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
